### ISSUE TITLE
Unable to call Track.Save() on a Track located in the Desktop

### ISSUE THREAD

**Issue by ComradeDracose** [Zeugma440/atldotnet#103]
Hi,
When I try to call Track.Save() on a Track that's located on my Desktop, it throws an error through the ATL.ConsoleLogger : 

`Access to the path 'C:\Users\adrie\Desktop\2 Arcueil Cachan (avec Shantel).mp3' is denied.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at ATL.AudioData.AudioDataManager.UpdateTagInFile(TagData theTag, Int32 tagType)
[ERROR] C:\Users\adrie\Desktop\2 Arcueil Cachan (avec Shantel).mp3 | Access to the path 'C:\Users\adrie\Desktop\2 Arcueil Cachan (avec Shantel).mp3' is denied. [δ=3329 ms]`

Alternatively, I also tried to call Track.Save() on a track that I know can save, when in another folder : 

`Access to the path 'C:\Users\adrie\Desktop\1 I like it like that.mp3' is denied.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at ATL.AudioData.AudioDataManager.UpdateTagInFile(TagData theTag, Int32 tagType)
[ERROR] C:\Users\adrie\Desktop\1 I like it like that.mp3 | Access to the path 'C:\Users\adrie\Desktop\1 I like it like that.mp3' is denied. [δ=2663 ms]`

These errors show up even when I ran my app as Administrator.

Is this intended behaviour ?

Best Regards :)

**Comment by Zeugma440** [comment]
Hello Comrade,

I fear that issue doesn't come from the library itself but from the .NET framework.

`AudioDataManager` simply opens a `FileStream` at the targeted location.

I guess the answer lies in how permissions are set on your machine.

Best regards,
