### ISSUE TITLE
Unable To Save Files With LRC Lyrics

### ISSUE THREAD

**Issue by nlogozzo** [Zeugma440/atldotnet#215]
Hello again :) Hope all is well!

There seems to be an issue with saving a file that has LRC Lyrics. Here is a file: [Bones.zip](https://github.com/Zeugma440/atldotnet/files/12371228/Bones.zip) (However, happens with all the files from #212)

Basically anytime we try to save the `Track` it fails with the error:
```
An item with the same key has already been added. Key: ti
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at ATL.LyricsInfo.ParseLRC(String data)
   at ATL.TagData.IntegrateValue(Field key, String value)
   at ATL.TagData.IntegrateValues(TagData targetData, Boolean integratePictures, Boolean mergeAdditionalData)
   at ATL.AudioData.IO.MetaDataIO.prepareWrite(Stream r, TagData tag)
   at ATL.AudioData.IO.MetaDataIO.Write(Stream s, TagData tag, ProgressToken`1 writeProgress)
   at ATL.AudioData.AudioDataManager.UpdateTagInFile(TagData theTag, TagType tagType, ProgressManager writeProgress)
```

Here was the code I used:
```csharp
var track = new Track(Path);
track.Album = "test" //can be anything: Title, Artist, Genre, etc...
track.Save(); 
//crash
```

atldotnet V5.1.0

**Comment by Zeugma440** [comment]
D'uh, what a dumb problem 🤦 

Fixed for next release~

**Comment by nlogozzo** [comment]
Could you release today? I'd like to get the next version of Tagger out :)

**Comment by Zeugma440** [comment]
I'd like to fix #216 too. I'll see what I can do.

**Comment by Zeugma440** [comment]
Version 5.02 is out !

Sorry for that issue that could have been avoided

**Comment by nlogozzo** [comment]
No worries, a big thank you for working with us and getting all these features and fixes implemented!!
