### ISSUE TITLE
Error Accessing FLAC

### ISSUE THREAD

**Issue by AaronPierdon** [Zeugma440/atldotnet#274]
Hi,
     I'm trying to access some FLAC files and I'm getting this exception, can you please help?
     
     System.IO.IOException: The parameter is incorrect. : 'M:\Music\D\DJ Food\Kaleidoscope 2000\04 - The Riff.flac'
   at System.IO.Strategies.FileStreamHelpers.ThrowInvalidArgument(SafeFileHandle handle)
   at System.IO.Strategies.OSFileStreamStrategy.Seek(Int64 offset, SeekOrigin origin)
   at System.IO.Strategies.BufferedFileStreamStrategy.Seek(Int64 offset, SeekOrigin origin)
   at ATL.AudioData.IO.MPEGaudio.findFrame(Stream source, VBRData& oVBR, SizeInfo sizeInfo) in C:\Users\Aaron\Desktop\atldotnet-5.25\atldotnet-5.25\ATL\AudioData\IO\MPEGaudio.cs:line 548
   at ATL.AudioData.IO.MPEGaudio.HasValidFrame(Stream source) in C:\Users\Aaron\Desktop\atldotnet-5.25\atldotnet-5.25\ATL\AudioData\IO\MPEGaudio.cs:line 489
   at ATL.AudioData.AudioDataIOFactory.GetFromStream(Stream s) in C:\Users\Aaron\Desktop\atldotnet-5.25\atldotnet-5.25\ATL\AudioData\AudioDataIOFactory.cs:line 427
   at ATL.AudioData.AudioFileIO..ctor(String path, Boolean readEmbeddedPictures, Boolean readAllMetaFrames) in C:\Users\Aaron\Desktop\atldotnet-5.25\atldotnet-5.25\ATL\AudioData\AudioFileIO.cs:line 51
   at ATL.Track.Update(Boolean onlyReadEmbeddedPictures) in C:\Users\Aaron\Desktop\atldotnet-5.25\atldotnet-5.25\ATL\Entities\Track.cs:line 409
   at ATL.Track..ctor(String path, Boolean load) in C:\Users\Aaron\Desktop\atldotnet-5.25\atldotnet-5.25\ATL\Entities\Track.cs:line 38
   at ATLGrabber.ATLGrabber.Main() in C:\Users\Aaron\OneDrive\source\repos\ATLGrabber\ATLGrabber\Program.cs:line 42

**Comment by AaronPierdon** [comment]
Why is it referencing my desktop? CurrentEnviornment shows not desktop: 


![image](https://github.com/user-attachments/assets/47c53778-79ea-4086-a9d9-35633689d431)

**Comment by AaronPierdon** [comment]
I figured it out. I was trying to access a corrupt file that I couldn't even open in Foobar.

I just continued execution. I had my foreach loop structured wrong so it was crashing my app.

Any chance you can make these work with Forms apps? I'm currently passing JSON files to another executable from my forms app and then having a console app run ATL API calls.

**Comment by Zeugma440** [comment]
> Any chance you can make these work with Forms apps? I'm currently passing JSON files to another executable from my forms app and then having a console app run ATL API calls.

You definitely can by adding a NuGet dependency to your project. For instance, you can check these Forms projects that use ATL :

https://github.com/Hazaaa/Youtube-To-Mp3-Winforms

https://github.com/Royce551/FRESHMusicPlayer-WinForms/tree/master/FRESHMusicPlayer/FRESHMusicPlayer

Happy coding~

**Comment by Zeugma440** [comment]
Closing this as I understand there's no actual issue.

Please open another one if you need further assistance.

**Comment by AaronPierdon** [comment]
Thanks go ahead and close it
