### ISSUE TITLE
Arithmetic operation resulted in an overflow.

### ISSUE THREAD

**Issue by Smiuv** [Zeugma440/atldotnet#278]
Arithmetic operation resulted in an overflow.
at ATL.BufferedBinaryReader.ReadBytes(Int32 nbBytes)
   at ATL.AudioData.IO.ID3v2.readFrame(BufferedBinaryReader source, TagInfo tag, ReadTagParams readTagParams, IList`1& comments, Boolean inChapter)
   at ATL.AudioData.IO.ID3v2.readFrames(BufferedBinaryReader source, TagInfo tag, Int64 offset, ReadTagParams readTagParams)
   at ATL.AudioData.IO.ID3v2.Read(Stream source, Int64 offset, ReadTagParams readTagParams)
   at ATL.AudioData.IO.ID3v2.read(Stream source, ReadTagParams readTagParams)
   at ATL.AudioData.IO.MetaDataIO.Read(Stream source, ReadTagParams readTagParams)
   at ATL.AudioData.AudioDataManager.read(Stream source, ReadTagParams readTagParams)
   at ATL.AudioData.AudioDataManager.read(Stream source, Boolean readEmbeddedPictures, Boolean readAllMetaFrames, Boolean prepareForWriting)
   at ATL.AudioData.AudioDataManager.ReadFromFile(Boolean readEmbeddedPictures, Boolean readAllMetaFrames)
Arithmetic operation resulted in an overflow.
   at ATL.BufferedBinaryReader.ReadBytes(Int32 nbBytes)
   at ATL.AudioData.IO.ID3v2.readFrame(BufferedBinaryReader source, TagInfo tag, ReadTagParams readTagParams, IList`1& comments, Boolean inChapter)
   at ATL.AudioData.IO.ID3v2.readFrames(BufferedBinaryReader source, TagInfo tag, Int64 offset, ReadTagParams readTagParams)
   at ATL.AudioData.IO.ID3v2.Read(Stream source, Int64 offset, ReadTagParams readTagParams)
   at ATL.AudioData.IO.ID3v2.read(Stream source, ReadTagParams readTagParams)
   at ATL.AudioData.IO.MetaDataIO.Read(Stream source, ReadTagParams readTagParams)
   at ATL.AudioData.AudioDataManager.read(Stream source, ReadTagParams readTagParams)
   at ATL.AudioData.AudioDataManager.read(Stream source, Boolean readEmbeddedPictures, Boolean readAllMetaFrames, Boolean prepareForWriting)
   at ATL.AudioData.AudioDataManager.ReadFromFile(Boolean readEmbeddedPictures, Boolean readAllMetaFrames)
Arithmetic operation resulted in an overflow.
   at ATL.BufferedBinaryReader.ReadBytes(Int32 nbBytes)
   at ATL.AudioData.IO.ID3v2.readFrame(BufferedBinaryReader source, TagInfo tag, ReadTagParams readTagParams, IList`1& comments, Boolean inChapter)
   at ATL.AudioData.IO.ID3v2.readFrames(BufferedBinaryReader source, TagInfo tag, Int64 offset, ReadTagParams readTagParams)
   at ATL.AudioData.IO.ID3v2.Read(Stream source, Int64 offset, ReadTagParams readTagParams)
   at ATL.AudioData.IO.ID3v2.read(Stream source, ReadTagParams readTagParams)
   at ATL.AudioData.IO.MetaDataIO.Read(Stream source, ReadTagParams readTagParams)
   at ATL.AudioData.AudioDataManager.read(Stream source, ReadTagParams readTagParams)
   at ATL.AudioData.AudioDataManager.read(Stream source, Boolean readEmbeddedPictures, Boolean readAllMetaFrames, Boolean prepareForWriting)
   at ATL.AudioData.AudioDataManager.ReadFromFile(Boolean readEmbeddedPictures, Boolean readAllMetaFrames)
Arithmetic operation resulted in an overflow.
   at ATL.BufferedBinaryReader.ReadBytes(Int32 nbBytes)
   at ATL.AudioData.IO.ID3v2.readFrame(BufferedBinaryReader source, TagInfo tag, ReadTagParams readTagParams, IList`1& comments, Boolean inChapter)
   at ATL.AudioData.IO.ID3v2.readFrames(BufferedBinaryReader source, TagInfo tag, Int64 offset, ReadTagParams readTagParams)
   at ATL.AudioData.IO.ID3v2.Read(Stream source, Int64 offset, ReadTagParams readTagParams)
   at ATL.AudioData.IO.ID3v2.read(Stream source, ReadTagParams readTagParams)
   at ATL.AudioData.IO.MetaDataIO.Read(Stream source, ReadTagParams readTagParams)
   at ATL.AudioData.AudioDataManager.read(Stream source, ReadTagParams readTagParams)
   at ATL.AudioData.AudioDataManager.read(Stream source, Boolean readEmbeddedPictures, Boolean readAllMetaFrames, Boolean prepareForWriting)
   at ATL.AudioData.AudioDataManager.ReadFromFile(Boolean readEmbeddedPictures, Boolean readAllMetaFrames)

**Comment by Zeugma440** [comment]
Good day to you too

If you were me I wonder what you'd do with just a stacktrace, without any other context.

FYI, here's how the issue submission screen looks like on GitHub

![image](https://github.com/user-attachments/assets/8661ca99-9e9f-45ca-9f20-10245668ce51)

Thank you for your understanding~

**Comment by Smiuv** [comment]
Hello, at that moment I reported the problem very quickly.

This happens to an mp3 file and none of its tags are loaded into Publisher.

I tested in other libraries and the tags (except for the photo) are completely visible. (The music has a picture).

To solve this problem, when I delete the photo, it seems to work correctly again (with another library and then again with the same library). Temporarily, to solve the problem with ffmpeg, I delete the music picture.

Detected format "MPEG Audio (Layer ?)".

**Comment by Zeugma440** [comment]
Thanks for your feedback. I'll need that file to be able to diagnose the issue.

Could you send it through a 3rd party host (e.g. wetransfer, mega...) at [my Github username] [at] [hotmail] [dot] [com] ?

Thanks in advance

**Comment by Smiuv** [comment]
http://hc1.checker.in/file2link/music/file_412861.mp3/Eycin_Sahand_Mese_Ghabl_Ft._Lara_.mp3

**Comment by Zeugma440** [comment]
Thanks for the file.

Problem is that the ID3v2 tag in your file has a badly formatted WXXX field, and ATL fails at handling it.

I've fixed that for next release. Stay tuned~

**Comment by Smiuv** [comment]
Thank you, it is a very good library. 
good luck.

**Comment by Smiuv** [comment]
Hello again, I use this library in a web application and I edit 1000 musics daily with this library, and I found some other bugs, if you want, I can send some of them.

**Comment by Zeugma440** [comment]
> Hello again, I use this library in a web application and I edit 1000 musics daily with this library, 

I'm so glad ATL can help you do that 😄 


> I found some other bugs, if you want, I can send some of them.

Yes please ❤️ 

Just be sure to open one github issue per bug, and include if possible the file hosted on a 3rd party site (not on Github).

**Comment by Smiuv** [comment]
Ok , thanks

**Comment by Smiuv** [comment]
I tried the file and it was correct from my side , thanks.
