### ISSUE TITLE
Error when reading a .dsf file

### ISSUE THREAD

**Issue by daviddassau** [Zeugma440/atldotnet#55]
Hello! First, thank you for supplying this project!

I am trying to read a .dsf file, using the code snippet you've supplied.

```
string fileName = "C:\\TestDSD\\DSF\\000334929725_01_01.dsf";

// Load audio file information into memory
Track theTrack = new Track(fileName);

Console.WriteLine("Title: " + theTrack.Title);
Console.WriteLine("Artist: " + theTrack.Artist);
```
But when it finished the "load audio file info" line, it gives me the following error:
`Number was less than the array's lower bound in the first dimension.`

I don't think it's an issue of your library not accepting the file format/extension, because .dsf is listed on your main page. Could you tell me what is going on?

Thank you in advance!

**Comment by Zeugma440** [comment]
Hi David,

ATL does support DSF files, and the code you've written does look good.

I'm gonna need a little more to understand the problem. 

- Do you have a complete stacktrace of the issue ?
- Could you upload the file somewhere so that I can repro that issue ?

NB : If you want to send it to me without posting a public link you can do so on zeugma440 /at/ hotmail.com

**Comment by daviddassau** [comment]
@Zeugma440  thank you for getting back to me! I'm going to send you an email with the audio file attached, so hopefully you'll be able to reproduce the problem.

**Comment by daviddassau** [comment]
@Zeugma440 actually, I might have to go another route. My .dsf file is too big to share over email or as an attachment here. I'll post the stacktrace instead:

```
Number was less than the array's lower bound in the first dimension.
Parameter name: srcIndex
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at ATL.BufferedBinaryReader.Read(Byte[] buffer, Int32 offset, Int32 count) in C:\repos\_Practice\TestDSDReader\atldotnet-master\atldotnet-master\ATL\Utils\BufferedBinaryReader.cs:line 158
   at ATL.StreamUtils.TraversePadding(Stream source) in C:\repos\_Practice\TestDSDReader\atldotnet-master\atldotnet-master\ATL\Utils\StreamUtils.cs:line 809
   at ATL.AudioData.IO.ID3v2.readFrame(BufferedBinaryReader source, TagInfo tag, ReadTagParams readTagParams, IList`1& comments, Boolean inChapter) in C:\repos\_Practice\TestDSDReader\atldotnet-master\atldotnet-master\ATL\AudioData\IO\ID3v2.cs:line 554
   at ATL.AudioData.IO.ID3v2.readFrames(BufferedBinaryReader source, TagInfo tag, Int64 offset, ReadTagParams readTagParams) in C:\repos\_Practice\TestDSDReader\atldotnet-master\atldotnet-master\ATL\AudioData\IO\ID3v2.cs:line 903
   at ATL.AudioData.IO.ID3v2.Read(BinaryReader source, Int64 offset, ReadTagParams readTagParams) in C:\repos\_Practice\TestDSDReader\atldotnet-master\atldotnet-master\ATL\AudioData\IO\ID3v2.cs:line 983
   at ATL.AudioData.IO.ID3v2.read(BinaryReader source, ReadTagParams readTagParams) in C:\repos\_Practice\TestDSDReader\atldotnet-master\atldotnet-master\ATL\AudioData\IO\ID3v2.cs:line 950
   at ATL.AudioData.IO.MetaDataIO.Read(BinaryReader source, ReadTagParams readTagParams) in C:\repos\_Practice\TestDSDReader\atldotnet-master\atldotnet-master\ATL\AudioData\MetaDataIO.cs:line 625
   at ATL.AudioData.AudioDataManager.read(BinaryReader source, ReadTagParams readTagParams) in C:\repos\_Practice\TestDSDReader\atldotnet-master\atldotnet-master\ATL\AudioData\AudioDataManager.cs:line 356
   at ATL.AudioData.AudioDataManager.read(BinaryReader source, Boolean readEmbeddedPictures, Boolean readAllMetaFrames, Boolean prepareForWriting) in C:\repos\_Practice\TestDSDReader\atldotnet-master\atldotnet-master\ATL\AudioData\AudioDataManager.cs:line 315
   at ATL.AudioData.AudioDataManager.ReadFromFile(Boolean readEmbeddedPictures, Boolean readAllMetaFrames) in C:\repos\_Practice\TestDSDReader\atldotnet-master\atldotnet-master\ATL\AudioData\AudioDataManager.cs:line 195
Not a PSF file
   at ATL.AudioData.IO.PSF.read(BinaryReader source, ReadTagParams readTagParams) in C:\repos\_Practice\TestDSDReader\atldotnet-master\atldotnet-master\ATL\AudioData\IO\PSF.cs:line 366
   at ATL.AudioData.IO.PSF.Read(BinaryReader source, SizeInfo sizeInfo, ReadTagParams readTagParams) in C:\repos\_Practice\TestDSDReader\atldotnet-master\atldotnet-master\ATL\AudioData\IO\PSF.cs:line 352
   at ATL.AudioData.AudioDataManager.read(BinaryReader source, ReadTagParams readTagParams) in C:\repos\_Practice\TestDSDReader\atldotnet-master\atldotnet-master\ATL\AudioData\AudioDataManager.cs:line 342
   at ATL.AudioData.AudioDataManager.read(BinaryReader source, Boolean readEmbeddedPictures, Boolean readAllMetaFrames, Boolean prepareForWriting) in C:\repos\_Practice\TestDSDReader\atldotnet-master\atldotnet-master\ATL\AudioData\AudioDataManager.cs:line 315
   at ATL.AudioData.AudioDataManager.ReadFromFile(Boolean readEmbeddedPictures, Boolean readAllMetaFrames) in C:\repos\_Practice\TestDSDReader\atldotnet-master\atldotnet-master\ATL\AudioData\AudioDataManager.cs:line 195
```

**Comment by Zeugma440** [comment]
Thanks for the stacktrace.

When I mentioned e-mailing, I didn't expect any attachment, as DSF files tend to be huge. You could use a 3rd party hosting site such as mega or dropbox and provide the link...

**Comment by daviddassau** [comment]
@Zeugma440  Oh, duh! I just uploaded it to Dropbox, and shared it with you via email!

**Comment by Zeugma440** [comment]
Got the file, thanks 👍 

I'll keep you updated soon

**Comment by Zeugma440** [comment]
Got it. You made me fix a nasty bug I couldn't put my finger on until now. Thanks a lot !

The fix is coming to NuGet as I type.

PS : Glad to meet someone else who appreciates Bach ;-)

**Comment by daviddassau** [comment]
@Zeugma440  thank you so much for your help! And I'm glad I could be of some assistance; normally, I am the one that is _creating_ the bugs, not pointing them out, so that's a nice chance of pace lol. And yes, I definitely appreciate some classical music. I actually work for a company called Naxos, we're a label and distributor for classical (and other like-minded genres) music!

**Comment by Zeugma440** [comment]
Awesome, I do have a couple of Naxos CD's on my shelf  :-)

Don't hesitate if you have other issues / features to discuss.

**Comment by daviddassau** [comment]
@Zeugma440  will do, thank you once again!
