### ISSUE TITLE
Exception thrown when saving tags with a new Dictionary for Track.AdditionalFields

### ISSUE THREAD

**Issue by squabbi** [Zeugma440/atldotnet#66]
## The problem

ATL throws an exception when writing tags via `track.Save();` when setting the AdditionalFields track property with a new Dictionary object.

## Environment

* ATL version (or git revision) that exhibits the issue: 3.7.0
* Last ATL version that did not exhibit the issue (if applicable): N/A
* OS/version used to run ATL: Windows 10, .NET Core 3.1

## Details

If necessary, describe the problem you have been experiencing in more detail.

I'm probably just using it wrong! I couldn't quite figure it out from the exception message printed onto the console. If I comment out this section of code (below), it will write the tags without issue.

**Console output:**
```
Index was outside the bounds of the array.
   at ATL.AudioData.IO.ID3v2.writeTextFrame(BinaryWriter writer, String frameCode, String text, Encoding tagEncoding, String language, String description, Boolean isInsideUnsynch)
   at ATL.AudioData.IO.ID3v2.writeFrames(TagData tag, BinaryWriter w, Encoding tagEncoding)
   at ATL.AudioData.IO.ID3v2.write(TagData tag, BinaryWriter w, String zone)
   at ATL.AudioData.IO.MetaDataIO.writeAdapter(BinaryWriter w, TagData tag, Zone zone)
   at ATL.AudioData.IO.FileSurgeon.RewriteZonesDirect(BinaryWriter w, WriteDelegate write, ICollection`1 zones, TagData dataToWrite, Boolean tagExists, Int64 globalOffsetCorrection, Boolean buffered)
   at ATL.AudioData.IO.FileSurgeon.RewriteZones(BinaryWriter w, WriteDelegate write, ICollection`1 zones, TagData dataToWrite, Boolean tagExists)
   at ATL.AudioData.IO.MetaDataIO.Write(BinaryReader r, BinaryWriter w, TagData tag, IProgress`1 writeProgress)
   at ATL.AudioData.AudioDataManager.UpdateTagInFile(TagData theTag, Int32 tagType)
```

## Code To Reproduce Issue [ Good To Have ]

```
var xTags = new Dictionary<string, string>();
xTags.Add("TIT1", series);
xTags.Add("TIT3", title);
xTags.Add("TDAT", "1010");
xTags.Add("TLEN", track.DurationMs.ToString());
xTags.Add("WOAF", webAddress);
xTags.Add("WOAR", webAddress);
xTags.Add("WOAS", webAddress);
xTags.Add("WPUB", webAddress);
xTags.Add("WCOM", webAddress);
xTags.Add("WCOP", webAddress);
xTags.Add("WXXX", webAddress);
track.AdditionalFields = xTags;
```

**Comment by Zeugma440** [comment]
Hi and thanks for the feedback 👍 

From what I can see, there are two minor issues in what you're doing :

1/ You're using `AdditionalFields` to write fields that are supported by more "direct" properties of `Track`.
e.g. using `xTags.Add("TIT1", series)` instead of `track.Description = series`

It _does_ the job but it's way more difficult to read and to port to other tagging systems than ID3v2.

2/ The cause of the crash is likely to be the "WXXX" frame. The library doesn't handle user-defined WXXX frames very well.
Do you want to test with the updated code or would you prefer a new NuGet release ?

**Comment by squabbi** [comment]
Hi, thanks for the prompt reply, I apologise for my tardiness!

Thank you for pointing out what I was doing wrong, I'll make use of the direct methods that will write to those specific tags.

Yeah, that `WXXX` frame wasn't happy being written by TagLibShap either. I'm not sure if you've released it on NuGet yet since last week, but if I were testing it with the updated code, I would just clone and build ATL?

**Comment by squabbi** [comment]
Just tested your latest commit and writing the WXXX tag works perfectly! Thank you. :)

**Comment by Zeugma440** [comment]
Awesome, thanks for your feedback !

I'll release it to NuGet right away.
