### ISSUE TITLE
Crash on a specific WAV file

### ISSUE THREAD

**Issue by Zeugma440** [Zeugma440/atldotnet#81]
Hi there!!!!

After a pause I’ve been working on my Music Info Finder tool again, and today I ran into a new issue within your ATL library.

I hadn’t switched to the latest version before, but after running into an exception when updating/saving metadata I got the latest version from Github. But unfortunately, the exception still occurs.

These are the metadata fields I’m setting on this WAV file:

  *   TrackNumber = 1
  *   Artist = “Ace Ventura”
  *   Title = “Going Back”
  *   Album = “Paradise Engineering”
  *   AlbumArtist = “Ace Ventura”
  *   Year = 2015
  *   Genre = “Psychedelic Trance”

And I’m also adding an embedded JPEG:
using (var streamReader = copiedAudioFile.FileSystem.File.OpenRead(Path.Combine(outputDirectory, "album.jpg")))
{
       byte[] buffer = new byte[streamReader.Length];
       int bytesRead = streamReader.Read(buffer);

       PictureInfo pictureInfo = PictureInfo.fromBinaryData(buffer);
       trackMetadata.EmbeddedPictures.Clear();
       trackMetadata.EmbeddedPictures.Add(pictureInfo);
}

I’ve processed hundreds of (WAV) files, all with the same code, without errors. So there must be something in this particular WAV that’s different than in the other files. But I can’t determine what.
The original file doesn’t seem to contain any (noticable) metadata, but as an additional test I’ve just tried to clear all “AdditionalFields” before updating it with my metadata. That doesn’t resolve the issue as well.

Any clue where I should look / debug? If I can fix it, then I’ll submit a change.

“Token StartElement in state EndRootElement would result in an invalid XML document. Make sure that the ConformanceLevel setting is set to ConformanceLevel.Fragment or ConformanceLevel.Auto if you want to write an XML fragment.”

   at System.Xml.XmlWellFormedWriter.ThrowInvalidStateTransition(Token token, State currentState)
   at System.Xml.XmlWellFormedWriter.AdvanceState(Token token)
   at System.Xml.XmlWellFormedWriter.WriteStartElement(String prefix, String localName, String ns)
   at System.Xml.XmlWriter.WriteStartElement(String localName)
   at ATL.AudioData.IO.IXmlTag.ToStream(BinaryWriter w, Boolean isLittleEndian, MetaDataIO meta) in C:\Repos\Github\atldotnet\ATL\AudioData\IO\Helpers\IXmlTag.cs:line 152
   at ATL.AudioData.IO.WAV.write(TagData tag, BinaryWriter w, String zone) in C:\Repos\Github\atldotnet\ATL\AudioData\IO\WAV.cs:line 467
   at ATL.AudioData.IO.MetaDataIO.writeAdapter(BinaryWriter w, TagData tag, Zone zone) in C:\Repos\Github\atldotnet\ATL\AudioData\MetaDataIO.cs:line 686
   at ATL.AudioData.IO.FileSurgeon.RewriteZones(BinaryWriter fullScopeWriter, WriteDelegate write, ICollection`1 zones, TagData dataToWrite, Boolean tagExists, Boolean useBuffer) in C:\Repos\Github\atldotnet\ATL\AudioData\Utils\FileSurgeon.cs:line 227
   at ATL.AudioData.IO.FileSurgeon.RewriteZones(BinaryWriter w, WriteDelegate write, ICollection`1 zones, TagData dataToWrite, Boolean tagExists) in C:\Repos\Github\atldotnet\ATL\AudioData\Utils\FileSurgeon.cs:line 138
   at ATL.AudioData.IO.MetaDataIO.Write(BinaryReader r, BinaryWriter w, TagData tag, IProgress`1 writeProgress) in C:\Repos\Github\atldotnet\ATL\AudioData\MetaDataIO.cs:line 756
   at ATL.AudioData.AudioDataManager.UpdateTagInFile(TagData theTag, Int32 tagType) in C:\Repos\Github\atldotnet\ATL\AudioData\AudioDataManager.cs:line 253

**Comment by Zeugma440** [comment]
This might be caused by a badly formatted XML entry inside this file's metadata, but there's no way of knowing for sure without examining the file itself.

Is there a way you can send it to me, for instance through a file sharing platform ?

**Comment by darzid** [comment]
Here you go: https://1drv.ms/u/s!AptO6CsSFw6MrfkaOVqUW-jDYToRwA?e=cCqRTP

Password = issue81

**Comment by darzid** [comment]
PS: I have multiple files with the same issue (started processing a new set of files).

**Comment by Zeugma440** [comment]
I got your file (thanks for that) and have reproduced the issue successfuly.

This file has an existing IXML tag that is well-formatted from a basic XML point of view. It seems the issue is a genuine bug of the library.

I'll work on it and let you know.

**Comment by Zeugma440** [comment]
Turns out the files I used to test had a flat, standard XML structure inside the IXML chunk whereas the one you used has a non-standard XML tree.

The latest commit to `master` should solve your issue. Let me know if it's fine on your side !

**Comment by darzid** [comment]
Hi!

The fix works!

**Comment by Zeugma440** [comment]
Awesome !

I'm gonna fix the other issues and include it in the next release.

**Comment by Zeugma440** [comment]
Included in today's v3.16
