### ISSUE TITLE
Error while updating mp3

### ISSUE THREAD

**Issue by JeepNL** [Zeugma440/atldotnet#9]
## The problem

Error while updating the following podcast (example)

LINK: https://podcast.npo.nl/file/nosop3techpodcast/5dc22df66c91c1adadc8d97bc50d486e/nporadio1_nos-op-3-tech-podcast-instagram-lanceert-igtv-en-een-nieuw-hoofdstuk-in-de-lootboxes-soap.mp3

## Environment

* ATL 2.4.1 Nuget
* Windows / Visual Studio.

## Details

CONSOLE OUTPUT: 

Field code fixed length is 4; detected field 'replaygain_track_gain' is 21 characters long and cannot be written
   at ATL.AudioData.IO.MetaDataIO.Write(BinaryReader r, BinaryWriter w, TagData tag)
   at ATL.AudioData.AudioDataManager.UpdateTagInFile(TagData theTag, Int32 tagType)

-----

Some more mp3 podcasts having the same error with different fields like this one:

LINK: https://podcast.npo.nl/file/joopcafe/1513/nporadio1_joopcafe_20180622_joop-cafe-67-met-francisco-van-jole-en-mei-li-vos.mp3

CONSOLE OUTPUT: 

Field code fixed length is 4; detected field 'CREATION_TIME' is 13 characters long and cannot be written
   at ATL.AudioData.IO.MetaDataIO.Write(BinaryReader r, BinaryWriter w, TagData tag)
   at ATL.AudioData.AudioDataManager.UpdateTagInFile(TagData theTag, Int32 tagType)

## Code To Reproduce Issue [ Good To Have ]

                    try
                    {
                        theTrack.Save();
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine("\n\r\n\rEXCEPTION: " + ex + "\n\r\n\r");
                    }

**Comment by JeepNL** [comment]
I've tried to remove those fields and then use .Save() but that didn't help.

    ie: theTrack.AdditionalFields.Remove("replaygain_track_gain");

**Comment by Zeugma440** [comment]
Hey there @JeepNL. First of all, thanks for using ATL !

I have reproduced the issue with the 2nd sample. I'll post a fix very soon.

**Comment by JeepNL** [comment]
Thank you for the fix! And WOW, on the same day! It now works with all of the mp3 podcasts I download with RSS.

Just began to use ATL (.Net Core) and I'm loving it! So thank you for your all of your work and for making this available.
